### ISSUE TITLE
Lack of compare implement code

### ISSUE THREAD

**Issue by huzk8** [zhugezifang/dataCompare#2]
when i start dataCompare  in my laptop, i can't find any compare page and code.

**Comment by zhugezifang** [comment]
hi，i will push   the latest code later

**Comment by zhugezifang** [comment]
hi，i had pushed the latest code

**Comment by zhugezifang** [comment]
> when i start dataCompare in my laptop, i can't find any compare page and code.

hi，i had pushed the latest code
